routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('/search', 'HomeController@search')->name('search');
Route::get('/show', 'HomeController@show')->name('search');
Route::resource('/', 'HomeController');
Route::post('/product_detail/commentProduct', 'HomeController@commentProduct')->name('comment_roduct');
Route::post('/all_product/sortProduct', 'HomeController@sortProduct')->name('sort_product');
Route::get('/product_detail/{id}', 'HomeController@productDetail')->name('product_detail');
Route::resource('/home', 'HomeController');
Route::resource('/comment', 'CommentController', array('as' => 'admin'));
Route::post('/product_detail/{id}/comment', 'CommentController@store');
Route::resource('admin/authors', 'AdminAuthorController', array('as' => 'admin'));
Route::resource('admin/languages', 'AdminLanguageController', array('as' => 'admin'));
Route::resource('admin/types', 'AdminTypeController', array('as' => 'admin'));
Route::resource('admin/publishers', 'AdminPublisherController', array('as' => 'admin'));
Route::resource('admin/products', 'AdminProductsController', array('as' => 'admin'));
Route::resource('admin/comment', 'CommentController', array('as' => 'admin'));
Route::resource('admin/users', 'AdminUsersController', array('as' => 'admin'));
Route::resource('admin/search', 'SearchController', array('as' => 'admin'));

Route::get('/author_detail/{id}/','MenuController@menuAuthors')->name('author_detail');
Route::get('/type_detail/{id}/','MenuController@menuTypes')->name('type_detail');
Route::get('/language_detail/{id}/','MenuController@menuLanguages')->name('language_detail');
Route::get('/publisher_detail/{id}/','MenuController@menuPublishers')->name('publisher_detail');


Route::get('/all_product', 'HomeController@allProduct')->name('all_product');
Route::get('/checkout', 'HomeController@checkOut')->name('checkout');
//Route::resource('/comment', 'CommentController' ,array('as'=>'admin'));
//Route::post('/product_detail/{id}/comment', 'CommentController@store');

Route::resource('admin/authors', 'AdminAuthorController',array('as'=>'admin'));
Route::resource('admin/languages', 'AdminLanguageController',array('as'=>'admin'));
Route::resource('admin/types', 'AdminTypeController',array('as'=>'admin'));
Route::resource('admin/publishers', 'AdminPublisherController',array('as'=>'admin'));
Route::resource('admin/products', 'AdminProductsController',array('as'=>'admin'));
Route::resource('admin/users', 'AdminUsersController' ,array('as'=>'admin'));
Route::resource('admin/search', 'SearchController' ,array('as'=>'admin'));

Route::get('admin/products/deletep/{id}', 'AdminProductsController@deletePicture');
Route::resource('user/management', 'UserManagementController');
Route::resource('user/management', 'UserManagementController');
Route::get('user/{id}', 'UserManagementController@show');
Route::get('user/edit/{id}', 'UserManagementController@edit');
Route::put('user/update/{id}', 'UserManagementController@update');
Route::get('admin/{id}', 'UserManagementController@show');
Route::get('/add-to-cart/{id}', [
    'uses' => 'ProductController@getAddToCart',
]);

Route::get('/delete-cart-product/{id}', [
    'uses' => 'ProductController@removeItem',
    'as' => 'product.removeItem'
]);

Route::get('/delete-cart/', [
    'uses' => 'ProductController@removeCart',
]);

Route::post('/shopping-cart', [
    'uses' => 'ProductController@changeProductQuantity',
    'as' => 'product.changeProductQuantity'
]);

Route::get('/shopping-cart', [
    'uses' => 'ProductController@getCart',
    'as' => 'product.shoppingcart'
]);

Route::get('/contact-us', 'HomeController@contactUs')->name('contact_us');
Route::post('/send-feed-back', 'HomeController@sendFeedback')->name('send_feed_back');
Route::get('/about-us', 'HomeController@aboutUs')->name('about_us');

Auth::routes();

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable {

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'address',
        'phone',
        'image',
        'is_admin',
        'is_thumbnail'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function photo() {
        return $this->belongsTo('App\Photo');
    }

    public function isAdmin() {
        if ($this->is_admin == 1 && $this->is_thumbnail == 1) {
            return true;
        }
        return false;
    }
    public function is_active() {
        if ($this->is_admin == 0 && $this->is_thumbnail == 1) {
            return true;
        }
        return false;
    }

}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')
@section('content')


    <h1>Add Admin</h1>
   <div class="row">
        @include('includes.form_error')
    </div>

    <div class="container">
         <div class="row">
         
        <form action="{{ route('admin.users.store') }}" method="post" enctype='multipart/form-data' >
            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
            <div class=" form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    <label for="name">UserName:</label>
                    <input type="text" id="name" name="name" class="form-control" placeholder="Enter Your Name" value="{{ old('name') }}">
                    <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>   
             <div class=" form-group {{ $errors->has('address') ? 'has-error' : '' }}">
                    <label for="address">Address:</label>
                    <input type="text" id="address" name="address" class="form-control" placeholder="Enter Your Address" value="{{ old('address') }}">
                    <span class="text-danger">{{ $errors->first('address') }}</span>
            </div>   
             <div class=" form-group {{ $errors->has('phone') ? 'has-error' : '' }}">
                    <label for="phone">Phone:</label>
                    <input type="number" id="phone" name="phone" class="form-control" placeholder="Enter Your Phone" value="{{ old('phone') }}">
                    <span class="text-danger">{{ $errors->first('phone') }}</span>
            </div>   
            <div class="  form-group {{ $errors->has('email') ? 'has-error' : '' }}">
                <label for="email">Email:</label>
                <input type="text" id="email" name="email" class="form-control" placeholder="Enter Your Email" value="{{ old('email') }}">
                <span class="text-danger">{{ $errors->first('email') }}</span>
            </div>
            <div class="  form-group {{ $errors->has('password') ? 'has-error' : '' }}">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" class="form-control" value="{{ old('password') }}" placeholder="Enter Password">
                <span class="text-danger">{{ $errors->first('password') }}</span>
           </div>
            <div class="form-group">
                <input type="submit" class="btn btn-success" value="Add Admin" />
            </div>
        </form>
    </div>    
    </div>





 @stop

resources/views/admin/users/index.blade.php
@extends('layouts.admin')
@section('content')
@if (session('alert'))
    <div class="alert alert-success">
        <?php 
        echo session('alert');
        ?>
    </div>
@endif
<div class="row">
    <div class="col-sm-9">
        <h1>Users</h1>
    </div>
    <div class="col-sm-3">
         <form action="{{ route('admin.users.create')}}" >
         <input type="hidden" name="_method" value="CREATE">
         <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
           <div class="form-group">
               <input type="submit" class="btn btn-danger" value="Add Admin" />
             </div>
    </form>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Photo</th>
            <th>Name</th>
            <th>Address</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Create_at</th>
            <th>Update_at</th>
    </thead>
    <tbody>
        @foreach($users as $key=>$user)
        <tr>
            <td>{{$user->id}}</td>
            <td><img width="50px" height="50px" class="img-rounded" src="http://placehold.it/400x400" alt=""></td>
            <td> <a href="{{ url('admin/users/'.$user->id.'/edit') }}"> {{$user->name}} </a> </td>
            <td>{{$user->address}}</td>
            <td>{{$user->email}}</td>
            <td>{{$user->phone}}</td>
            <td>{{$user->created_at}}</td>
            <td>{{$user->updated_at}}</td>
            <td style="width: 50px!important;">
                <form action="{{ route('admin.users.destroy', $user->id) }}" method="POST" >
         <input type="hidden" name="_method" value="DELETE">
         <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
           <div class="form-group">
               <input type="submit" class="btn btn-danger" value="Delete User" />
               
             </div>
    </form>
            </td>  
        </tr>
        @endforeach  
    </tbody>
</table>
@stop